import type { Employee } from "@/components/dashboard/columns";

export const employees: Employee[] = [
  {
    id: "1",
    name: "John Doe",
    email: "m@example.com",
    password: "password123",
    user_designation: "Chief Executive Officer",
    department: "Management",
    is_role_model: true,
    contact_number: "+1-123-456-7890",
    date_of_birth: "1980-01-15",
  },
  {
    id: "2",
    name: "Jane Smith",
    email: "example@gmail.com",
    password: "password456",
    user_designation: "Chief Technology Officer",
    department: "Technology",
    is_role_model: true,
    contact_number: "+1-222-333-4444",
    date_of_birth: "1985-04-20",
  },
  {
    id: "3",
    name: "Bob Johnson",
    email: "example@example.com",
    password: "password789",
    user_designation: "Senior Product Manager",
    department: "Product",
    is_role_model: false,
    contact_number: "+1-555-666-7777",
    date_of_birth: "1988-09-10",
  },
  {
    id: "4",
    name: "Emily Davis",
    email: "emily.davis@example.com",
    password: "pass123",
    user_designation: "Full Stack Developer",
    department: "Engineering",
    is_role_model: false,
    contact_number: "+1-111-222-3333",
    date_of_birth: "1992-03-12",
  },
  {
    id: "5",
    name: "Daniel Lee",
    email: "daniel.lee@example.com",
    password: "pass456",
    user_designation: "Backend Developer",
    department: "Engineering",
    is_role_model: false,
    contact_number: "+1-444-555-6666",
    date_of_birth: "1990-07-08",
  },
  {
    id: "6",
    name: "Sophia Martinez",
    email: "sophia.m@example.com",
    password: "pass789",
    user_designation: "Frontend Developer",
    department: "Engineering",
    is_role_model: true,
    contact_number: "+1-777-888-9999",
    date_of_birth: "1993-11-21",
  },
  {
    id: "7",
    name: "William Brown",
    email: "will.b@example.com",
    password: "pass321",
    user_designation: "Database Administrator",
    department: "Engineering",
    is_role_model: false,
    contact_number: "+1-222-444-8888",
    date_of_birth: "1987-05-17",
  },
  {
    id: "8",
    name: "Olivia Wilson",
    email: "olivia.w@example.com",
    password: "pass654",
    user_designation: "UI/UX Designer",
    department: "Design",
    is_role_model: false,
    contact_number: "+1-555-123-4567",
    date_of_birth: "1994-02-02",
  },
  {
    id: "9",
    name: "James Taylor",
    email: "james.t@example.com",
    password: "pass987",
    user_designation: "DevOps Engineer",
    department: "Infrastructure",
    is_role_model: true,
    contact_number: "+1-888-999-0000",
    date_of_birth: "1989-10-25",
  },
  {
    id: "10",
    name: "Ava Anderson",
    email: "ava.a@example.com",
    password: "pass111",
    user_designation: "QA Engineer",
    department: "Quality Assurance",
    is_role_model: false,
    contact_number: "+1-333-222-1111",
    date_of_birth: "1995-08-13",
  },
  {
    id: "11",
    name: "Michael Thomas",
    email: "michael.t@example.com",
    password: "pass222",
    user_designation: "Frontend Developer",
    department: "Engineering",
    is_role_model: false,
    contact_number: "+1-123-321-4567",
    date_of_birth: "1991-06-29",
  },
  {
    id: "12",
    name: "Isabella Garcia",
    email: "isabella.g@example.com",
    password: "pass333",
    user_designation: "Graphic Designer",
    department: "Design",
    is_role_model: false,
    contact_number: "+1-456-789-1234",
    date_of_birth: "1996-09-05",
  },
  {
    id: "13",
    name: "Benjamin Harris",
    email: "ben.h@example.com",
    password: "pass444",
    user_designation: "Cloud Architect",
    department: "Infrastructure",
    is_role_model: true,
    contact_number: "+1-654-321-9876",
    date_of_birth: "1984-12-19",
  },
  {
    id: "14",
    name: "Mia Clark",
    email: "mia.c@example.com",
    password: "pass555",
    user_designation: "Mobile Developer",
    department: "Engineering",
    is_role_model: false,
    contact_number: "+1-987-654-3210",
    date_of_birth: "1997-01-30",
  },
  {
    id: "15",
    name: "Ethan Lewis",
    email: "ethan.l@example.com",
    password: "pass666",
    user_designation: "Machine Learning Engineer",
    department: "AI/ML",
    is_role_model: true,
    contact_number: "+1-741-852-9630",
    date_of_birth: "1992-04-18",
  },
  {
    id: "16",
    name: "Charlotte Walker",
    email: "charlotte.w@example.com",
    password: "pass777",
    user_designation: "Brand Designer",
    department: "Design",
    is_role_model: false,
    contact_number: "+1-963-852-7410",
    date_of_birth: "1994-11-09",
  },
  {
    id: "17",
    name: "Alexander King",
    email: "alex.k@example.com",
    password: "pass888",
    user_designation: "Cybersecurity Analyst",
    department: "Security",
    is_role_model: true,
    contact_number: "+1-852-456-1597",
    date_of_birth: "1986-03-22",
  },
  {
    id: "18",
    name: "Amelia Scott",
    email: "amelia.s@example.com",
    password: "pass999",
    user_designation: "Motion Designer",
    department: "Design",
    is_role_model: false,
    contact_number: "+1-753-951-4563",
    date_of_birth: "1995-07-11",
  },
  {
    id: "19",
    name: "Lucas Young",
    email: "lucas.y@example.com",
    password: "pass000",
    user_designation: "Performance Engineer",
    department: "Engineering",
    is_role_model: false,
    contact_number: "+1-159-357-8520",
    date_of_birth: "1993-02-16",
  },
  {
    id: "20",
    name: "Harper Allen",
    email: "harper.a@example.com",
    password: "pass101",
    user_designation: "Technical Writer",
    department: "Documentation",
    is_role_model: false,
    contact_number: "+1-258-654-1479",
    date_of_birth: "1991-05-20",
  },
  {
    id: "21",
    name: "Henry Hall",
    email: "henry.h@example.com",
    password: "pass202",
    user_designation: "Frontend Developer",
    department: "Engineering",
    is_role_model: true,
    contact_number: "+1-369-258-1470",
    date_of_birth: "1990-10-03",
  },
  {
    id: "22",
    name: "Evelyn Green",
    email: "evelyn.g@example.com",
    password: "pass303",
    user_designation: "SEO Specialist",
    department: "Marketing",
    is_role_model: false,
    contact_number: "+1-951-753-4567",
    date_of_birth: "1992-12-08",
  },
  {
    id: "23",
    name: "Jack Adams",
    email: "jack.a@example.com",
    password: "pass404",
    user_designation: "Java Developer",
    department: "Engineering",
    is_role_model: false,
    contact_number: "+1-852-159-3570",
    date_of_birth: "1989-08-14",
  },
];
