export const documents: DocumentItem[] = [
  { id: "1", name: "Company Policies", type: "folder" },
  { id: "2", name: "Culture Documents", type: "folder" },
  { id: "3", name: "HR Guidelines", type: "folder" },
  { id: "4", name: "Training Materials", type: "folder" },
  { id: "5", name: "Employee Handbooks", type: "folder" },
  { id: "6", name: "Benefits & Compensation", type: "folder" },
  { id: "7", name: "Code of Conduct", type: "folder" },
  { id: "8", name: "Performance Reviews", type: "folder" },
  { id: "9", name: "Desired Culture.pdf", type: "file" },
  { id: "10", name: "Company Values.pdf", type: "file" },
  { id: "11", name: "Mission Statement.pdf", type: "file" },
  { id: "12", name: "Vision 2025.pdf", type: "file" },
  { id: "13", name: "Employee Onboarding.pdf", type: "file" },
  { id: "14", name: "Remote Work Policy.pdf", type: "file" },
  { id: "15", name: "Diversity & Inclusion.pdf", type: "file" },
  { id: "16", name: "Professional Development.pdf", type: "file" },
  { id: "17", name: "Work-Life Balance.pdf", type: "file" },
  { id: "18", name: "Team Collaboration.pdf", type: "file" },
  { id: "19", name: "Innovation Guidelines.pdf", type: "file" },
  { id: "20", name: "Communication Standards.pdf", type: "file" },
  { id: "21", name: "Leadership Principles.pdf", type: "file" },
  { id: "22", name: "Feedback Culture.pdf", type: "file" },
  { id: "23", name: "Recognition Program.pdf", type: "file" },
  { id: "24", name: "Career Pathways.pdf", type: "file" },
  { id: "25", name: "Wellness Initiatives.pdf", type: "file" },
  { id: "26", name: "Safety Protocols.pdf", type: "file" },
  { id: "27", name: "Social Responsibility.pdf", type: "file" },
  { id: "28", name: "Environmental Policy.pdf", type: "file" },
  { id: "29", name: "Ethics Guidelines.pdf", type: "file" },
  { id: "30", name: "Confidentiality Agreement.pdf", type: "file" },
];
